# -*- coding: utf-8 -*-
"""DAY3HW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTvxBaaO-BlOmv7R4Pwlpjf9ztlUXyA8
"""

# ==========================================================
# Employee Retention Prediction using Logistic Regression
# Google Colab Code (Complete)
# ==========================================================

# ----------------------------
# Step 1: Import Libraries
# ----------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ----------------------------
# Step 2: Upload and Load Dataset
# ----------------------------
# Upload the file "HR_comma_sep.csv" from your computer
uploaded = files.upload()

# Read the dataset
df = pd.read_csv("/content/HR_comma_sep.csv")

# Display first five rows
print("First 5 Rows of Dataset")
display(df.head())

# ----------------------------
# Step 3: Basic Information
# ----------------------------

# Dataset shape
print("Dataset Shape:", df.shape)

# Dataset information
print("\nDataset Information")
df.info()

# Check for missing values
print("\nMissing Values")
print(df.isnull().sum())

# Statistical summary
print("\nStatistical Summary")
display(df.describe())

# ----------------------------
# Step 4: Exploratory Data Analysis (EDA)
# ----------------------------

# Average values for employees who stayed and left
print("\nAverage Values Grouped by Employee Retention")
display(df.groupby("left").mean(numeric_only=True))

# Correlation Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# ----------------------------
# Step 5: Salary vs Employee Retention
# ----------------------------

pd.crosstab(df.salary, df.left).plot(kind='bar', figsize=(6,5))

plt.title("Salary vs Employee Retention")
plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.legend(["Stayed", "Left"])
plt.show()

# ----------------------------
# Step 6: Department vs Employee Retention
# ----------------------------

pd.crosstab(df.Department, df.left).plot(kind='bar', figsize=(10,6))

plt.title("Department vs Employee Retention")
plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.legend(["Stayed", "Left"])
plt.show()

# ----------------------------
# Step 7: Feature Selection
# ----------------------------
# Selected important features based on EDA

sub_df = df[[
    'satisfaction_level',
    'average_montly_hours',
    'promotion_last_5years',
    'salary'
]]

# ----------------------------
# Step 8: Convert Categorical Data
# ----------------------------
# Convert salary column into dummy variables

salary_dummies = pd.get_dummies(sub_df['salary'], prefix='salary')

# Combine numerical and dummy variables
X = pd.concat([
    sub_df[['satisfaction_level',
            'average_montly_hours',
            'promotion_last_5years']],
    salary_dummies
], axis=1)

# Drop one dummy variable to avoid dummy variable trap
X = X.drop('salary_high', axis=1)

# Target variable
y = df['left']

print("\nFeature Matrix")
display(X.head())

# ----------------------------
# Step 9: Split Dataset
# ----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# ----------------------------
# Step 10: Train Logistic Regression Model
# ----------------------------

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# ----------------------------
# Step 11: Prediction
# ----------------------------

y_pred = model.predict(X_test)

# ----------------------------
# Step 12: Model Accuracy
# ----------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", round(accuracy*100,2), "%")

# ----------------------------
# Step 13: Confusion Matrix
# ----------------------------

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues')

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ----------------------------
# Step 14: Classification Report
# ----------------------------

print("\nClassification Report")
print(classification_report(y_test, y_pred))

# ----------------------------
# Step 15: Sample Predictions
# ----------------------------

print("\nFirst 10 Predictions")
print(y_pred[:10])

print("\nActual Values")
print(y_test.values[:10])